name: Build workflow.
on: 
  workflow_dispatch: {}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: cake-build/cake-action@v1.1.1
        with:
          target: Default
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.3
        with:
          name: windows-terminal-quake.exe
          path: bin\windows-terminal-quake.exe
