name: Build workflow.
on: 
  workflow_dispatch: {}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Cake Action
        uses: cake-build/cake-action@v1.1.1
        with:
          target: Default
